- flake8_simplify.py
- tests/test_simplify.py
> WIP: ENH: Add any/all test

- flake8_simplify.py
- tests/test_simplify.py
> ENH: Enforce capitalization of environment variables

- .github/workflows/unit-test.yml
- flake8_simplify.py
- tests/test_simplify.py
> ENH: Add SIM113 (enumerate in for-loops)

- .github/workflows/unit-test.yml
- .pre-commit-config.yaml
- flake8_simplify.py
- requirements-dev.in
- requirements-dev.txt
- setup.cfg
- tests/test_simplify.py
> ENH: Duplicate blocks in conditionals

- flake8_simplify.py
- tests/test_simplify.py
> ENH: Only trigger SIM201-207 when it's not raising an exception

- flake8_simplify.py
- tests/test_simplify.py
> ENH: Check if a context handler is used for file opening

- README.md
- flake8_simplify.py
- setup.cfg
- tests/test_simplify.py
> SIM116: Use a dictionary lookup

- README.md
- flake8_simplify.py
- setup.cfg
- tests/test_simplify.py
> ENH: Add SIM117 (merge with-statements)

- flake8_simplify.py
- setup.cfg
- tests/test_simplify.py
> BUG: Fix all(not el for el in it) in SIM111

- README.md
- flake8_simplify.py
- setup.cfg
- tests/test_simplify.py
> ENH: Add SIM118 (key in dict.keys -> key in dict)

- setup.cfg
Correct a typo in the package description
> ✏️  simpified > simplified

- flake8_simplify.py
- tests/test_simplify.py
> SIM113: Remove False-Positive when continue is present

- flake8_simplify.py
> Fix SIM111 warning for compound expressions.

- README.md
- flake8_simplify.py
- setup.cfg
- tests/test_simplify.py
> SIM401: Implement check if-block -> dict.get(key, default)

- flake8_simplify.py
- tests/test_simplify.py
> BUG: Check list length for SIM114

- flake8_simplify.py
- tests/test_simplify.py
> [SIM109] Only rewrite when comparing against names

- flake8_simplify.py
- tests/test_simplify.py
* False-positives were elimitated (closes #83)
* Issues around quotation marks were fixed (closes #84, #89)
> SIM401: Fix false-positives and quotation issues

- flake8_simplify.py
- tests/test_simplify.py
> SIM104: yield from is not possible for async functions

- README.md
> SIM105: Add notice about speed impact in README

- flake8_simplify.py
- tests/test_simplify.py
BUG: Don't show SIM110 when an exception is returned instead of
returning
Closes #34
> SIM110: Remove false-positives

- README.md
- flake8_simplify.py
- tests/test_simplify.py
> SIM124 (SIM904): Check for dictionary pre-initialization

- .pre-commit-config.yaml
* fix the blacken doc hook so it's consistent
> fix blacken-docs hook

- CHANGELOG.md
- flake8_simplify.py
- tests/test_simplify.py
This introduces false-negatives, but that is typically better for
a linter
Closes #99
Closes #100
> SIM904: Remove false-positives

- README.md
- flake8_simplify.py
- tests/test_simplify.py
Credits to Skylion007 for defining this rule!
Closes #101
> SIM906: Merge nested os.path.join calls

- flake8_simplify/__init__.py
- flake8_simplify/rules/ast_for.py
- tests/test_100_rules.py
Thank you, Skylion007!
Closes #25
> SIM113: Remove false-positive in double-loop

- flake8_simplify/rules/ast_if.py
- tests/test_100_rules.py
> SIM102: Ignore 'if __name__ == "__main__"'

- README.md
- flake8_simplify/__init__.py
- flake8_simplify/rules/ast_assign.py
- flake8_simplify/utils.py
- tests/test_900_rules.py
> SIM909: Avoid reflexive assignments

- flake8_simplify/rules/ast_for.py
- tests/test_100_rules.py
> SIM111: Fix false-positive

- README.md
- flake8_simplify/__init__.py
- flake8_simplify/rules/ast_call.py
- tests/test_900_rules.py
> SIM902: Removed due to false-positives

- flake8_simplify/rules/ast_if.py
- tests/test_900_rules.py
> SIM908: Show false-positive

- README.md
Acc. to GitHub actions config the software is tested on 3.7 - 3.10
> Update supported Python versions
